{
 "title": "NATS Servers",
 "description": "NATS Server Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "OS Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Server CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "gnatsd_varz_cpu", "legendFormat": "{{server_id}}" }
   ]
  },
  {
   "title": "Server Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "gnatsd_varz_mem", "legendFormat": "{{server_id}}" }
   ]
  },
  { "title": "Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Bytes/s In",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(gnatsd_varz_in_bytes[1m])",
     "legendFormat": "{{server_id}}"
    }
   ]
  },
  {
   "title": "NATS Msgs/s In",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 9 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    { "expr": "irate(gnatsd_varz_in_msgs[1m])", "legendFormat": "{{server_id}}" }
   ]
  },
  {
   "title": "Bytes/s Out",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(gnatsd_varz_out_bytes[1m])",
     "legendFormat": "{{server_id}}"
    }
   ]
  },
  {
   "title": "NATS Msgs/s Out",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 9 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "irate(gnatsd_varz_out_msgs[1m])",
     "legendFormat": "{{server_id}}"
    }
   ]
  },
  { "title": "Client Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "gnatsd_varz_connections", "legendFormat": "{{server_id}}" }
   ]
  },
  {
   "title": "Subscriptions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "gnatsd_varz_subscriptions", "legendFormat": "{{server_id}}" }
   ]
  },
  {
   "title": "Slow Consumers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "gnatsd_varz_slow_consumers", "legendFormat": "{{server_id}}" }
   ]
  }
 ]
}