{
 "title": "K8s Containers",
 "description": "Summary metrics about pod containers running on Kubernetes nodes.",
 "tags": [
  "kubernetes",
  "k8s"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node",
    "query": "label_values(container_cpu_system_seconds_total{container!~\".+\"}, kubernetes_io_hostname)"
   },
   {
    "name": "namespace",
    "query": "label_values(container_cpu_system_seconds_total{container!~\".+\"}, namespace)"
   },
   {
    "name": "pod",
    "query": "label_values(container_cpu_system_seconds_total{kubernetes_io_hostname=~\"$node\", namespace=~\"$namespace\", container!~\".+\"}, pod)"
   },
   { "name": "pod_search" },
   {
    "name": "container",
    "query": "label_values(container_cpu_system_seconds_total{kubernetes_io_hostname=~\"$node\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\".+\"}, container)"
   },
   { "name": "container_search" }
  ]
 },
 "panels": [
  {
   "title": "Total Memory Usage",
   "type": "graph",
   "description": "Total memory usage of containers across a cluster",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{kubernetes_io_hostname=~\"$node\", namespace=~\"$namespace\", pod=~\"$pod\", pod=~\".*$pod_search.*\", container=~\".+\", container=~\"$container\", container=~\".*$container_search.*\"}) by (pod, container)",
     "legendFormat": "{{pod}}/{{container}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{kubernetes_io_hostname=~\"$node\", namespace=~\"$namespace\", pod=~\"$pod\", pod=~\".*$pod_search.*\", container=~\".+\", container=~\"$container\", container=~\".*$container_search.*\"}[2m])) by (pod, container)",
     "legendFormat": "{{pod}}/{{container}}"
    }
   ]
  },
  {
   "title": "Network Traffic (Inbound)",
   "type": "graph",
   "description": "Pod network usage. Kubernetes cAdvisor does not provide container-level network statistics for now, see\nhttps://github.com/kubernetes/kubernetes/issues/43560",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{kubernetes_io_hostname=~\"$node\", namespace=~\"$namespace\", pod=~\"$pod\", pod=~\".*$pod_search.*\", container=~\".+\"}[2m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Network Traffic (Outbound)",
   "type": "graph",
   "description": "Pod network usage. Kubernetes cAdvisor does not provide container-level network statistics for now, see\nhttps://github.com/kubernetes/kubernetes/issues/43560",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{kubernetes_io_hostname=~\"$node\", namespace=~\"$namespace\", pod=~\"$pod\", pod=~\".*$pod_search.*\", container=~\".+\"}[2m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Read IOPS",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "rate(container_fs_io_time_seconds_total{kubernetes_io_hostname=~\"$node\", namespace=~\"$namespace\", pod=~\"$pod\", pod=~\".*$pod_search.*\", container=~\".+\", container=~\"$container\", container=~\".*$container_search.*\"}[2m])",
     "legendFormat": "{{pod}}/{{container}}"
    }
   ]
  },
  {
   "title": "Write IOPS",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "wps" }
   ],
   "targets": [
    {
     "expr": "rate(container_fs_write_seconds_total{kubernetes_io_hostname=~\"$node\", namespace=~\"$namespace\", pod=~\"$pod\", pod=~\".*$pod_search.*\", container=~\".+\", container=~\"$container\", container=~\".*$container_search.*\"}[2m])",
     "legendFormat": "{{pod}}/{{container}}"
    }
   ]
  }
 ]
}