{
 "title": "Moleculer Actions",
 "tags": [ "moleculer" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "service",
    "query": "query_result(count(moleculer_service_endpoints_total) by (service) or count(moleculer_req_duration_ms_sum) by (service))"
   },
   {
    "name": "action",
    "query": "query_result(count(moleculer_action_endpoints_total{action=~\"$service\\\\..*\"}) by (action) or count(moleculer_req_duration_ms_sum{action=~\"$service\\\\..*\"}) by (action))"
   }
  ]
 },
 "panels": [
  {
   "title": "Services",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(count(moleculer_service_endpoints_total{service=~\"$service\"}) by (service) or count(moleculer_req_duration_ms_sum{service=~\"$service\"}) by (service))"
    }
   ]
  },
  {
   "title": "Actions",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(count(moleculer_action_endpoints_total{action=~\"$service\\\\..*\", action=~\"$action\"}) by (action) or count(moleculer_req_duration_ms_sum{action=~\"$service\\\\..*\", action=~\"$action\"}) by (action))"
    }
   ]
  },
  {
   "title": "Rps",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 9, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(irate(moleculer_req_duration_ms_count{service=~\"$service\", action=~\"$action\"}[1m]))"
    }
   ]
  },
  {
   "title": "Response time",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 14, "y": 0 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(irate(moleculer_req_duration_ms_sum{service=~\"$service\", action=~\"$action\"}[1m]))"
    }
   ]
  },
  {
   "title": "Total errors",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 19, "y": 0 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(moleculer_req_errors_total{service=~\"$service\", action=~\"$action\"})"
    }
   ]
  },
  {
   "title": "Service Action Response time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(irate(moleculer_req_duration_ms_sum{service=~\"$service\", action=~\"$action\"}[1m])) by (action)",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "Service Action calls",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(moleculer_req_duration_ms_count{service=~\"$service\", action=~\"$action\"}[1m])) by (action)",
     "legendFormat": "{{action}} Calls/s"
    },
    {
     "expr": "sum(irate(moleculer_req_errors_total{service=~\"$service\", action=~\"$action\"}[1m])) by (action)",
     "legendFormat": "{{action}} Errors/s"
    }
   ]
  },
  {
   "title": "Error types",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(moleculer_req_errors_total{service=~\"$service\", action=~\"$action\"}[1m])) by (action, errorName) ",
     "legendFormat": "{{action}}/{{errorName}}"
    }
   ]
  }
 ]
}