{
 "title": "Moleculer Overview",
 "tags": [ "moleculer" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "node_group",
    "query": "label_values(moleculer_nodes,nodeID)"
   },
   {
    "name": "node",
    "query": "label_values(moleculer_nodes{nodeID=~\"$node_group.*\"},nodeID)"
   },
   {
    "name": "service",
    "query": "label_values(moleculer_service_endpoints_total,service)"
   },
   {
    "name": "action",
    "query": "label_values(moleculer_action_endpoints_total{service=~\"$service\"},action)"
   },
   {
    "name": "event_group",
    "query": "label_values(moleculer_event_endpoints_total,group)"
   },
   {
    "name": "event",
    "query": "label_values(moleculer_event_endpoints_total{group=~\"$event_group\"},event)"
   }
  ]
 },
 "panels": [
  {
   "title": "Nodes",
   "type": "singlestat",
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(moleculer_nodes{nodeID=~\"$node_group.*\", nodeID=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Services",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(moleculer_service_endpoints_total{service=~\"$service\"})"
    }
   ]
  },
  {
   "title": "Actions",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(moleculer_action_endpoints_total{service=~\"$service\", action=~\"$action\"})"
    }
   ]
  },
  {
   "title": "Events",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(moleculer_event_endpoints_total{group=~\"$event_group\", event=~\"$event\"})"
    }
   ]
  },
  {
   "title": "Total calls",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 3 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(moleculer_req_total{service=~\"$service\", nodeID=~\"$node_group.*\", nodeID=~\"$node\", action=~\"$action\"})"
    }
   ]
  },
  {
   "title": "Total errors",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 3 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(moleculer_req_errors_total{service=~\"$service\", nodeID=~\"$node_group.*\", nodeID=~\"$node\", action=~\"$action\"})"
    }
   ]
  },
  {
   "title": "Response time",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 3 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(irate(moleculer_req_duration_ms_sum{service=~\"$service\", nodeID=~\"$node_group.*\", nodeID=~\"$node\", action=~\"$action\"}[1m]))"
    }
   ]
  },
  {
   "title": "Rps",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(irate(moleculer_req_total{service=~\"$service\", nodeID=~\"$node_group.*\", nodeID=~\"$node\", action=~\"$action\"}[1m]))"
    }
   ]
  },
  {
   "title": "Response time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(irate(moleculer_req_duration_ms_sum{service=~\"$service\", nodeID=~\"$node_group.*\", nodeID=~\"$node\", action=~\"$action\"}[1m]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Action calls",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(moleculer_req_total{service=~\"$service\", nodeID=~\"$node_group.*\", nodeID=~\"$node\", action=~\"$action\"}[1m]))",
     "legendFormat": "Calls"
    },
    {
     "expr": "sum(irate(moleculer_req_errors_total{service=~\"$service\", nodeID=~\"$node_group.*\", nodeID=~\"$node\", action=~\"$action\"}[1m]))",
     "legendFormat": "Errors"
    }
   ]
  },
  {
   "title": "Error types",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (errorName) (irate(moleculer_req_errors_total{service=~\"$service\", nodeID=~\"$node_group.*\", nodeID=~\"$node\", action=~\"$action\"}[1m]))",
     "legendFormat": "{{errorName}}"
    }
   ]
  },
  {
   "title": "Available nodes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(moleculer_nodes{nodeID=~\"$node_group.*\", nodeID=~\"$node\"})"
    }
   ]
  }
 ]
}